### ISSUE TITLE
Smart QQ将于2019年1月1日停止服务？？？

### ISSUE THREAD

**Issue by Jefffish09** [pandolia/qqbot#389]
[Smart QQ官网 - https://web2.qq.com](https://web2.qq.com/)

刚刚看到的消息，如果真的停止服务的话，那这个项目会转用私有协议吗？

![image](https://user-images.githubusercontent.com/44800122/49851519-4b42ab80-fe1c-11e8-8d61-0417399da96e.png)

**Comment by Raka-loah** [comment]
担心这个项目直接就成为时代的眼泪了……

**Comment by Tiande** [comment]
可不可以转移到 Telegram 呢… 
虽然有相关 Repo，但是这个用的很顺手了…

**Comment by pandolia** [comment]
这个项目时基于腾讯的 webqq 协议的，不会转私有协议的。

**Comment by ijacksonliu** [comment]
作为一个大学生，最令我荣耀的事情便是基于pandolia的QQBOT的写了一个QQ机器人，每天提醒着同学们起床，今天上什么课了，也正因为如此得到了辅导员的赏识

**Comment by Jefffish09** [comment]
@pandolia 多谢您多年对这个项目的付出！！

**Comment by Jefffish09** [comment]
@ijacksonliu 棒！

**Comment by pandolia** [comment]
@Jefffish09 多谢支持！

**Comment by majin1989** [comment]
之前好像看到过有使用安卓QQ客户端的接口的方法，希望能有类似的方式代替吧

**Comment by zaaazaa** [comment]
我上个月才看到有这个项目，这个月就告诉我腾讯要停止服务了？

**Comment by LinzheFu** [comment]
@pandolia 有点可惜。辛苦你了！

**Comment by ch-yx** [comment]
谢谢你！
这段时间真的很谢谢你！

**Comment by ehds** [comment]
刚想用，没想到腾讯就要关闭webQQ了。

**Comment by vincent-pli** [comment]
不会吧，我今天才看到这个项目，这就不能用了

**Comment by rongzeng54** [comment]
感谢  @pandolia

**Comment by todayzhou** [comment]
好可惜！
谢谢 @pandolia

**Comment by icaics** [comment]
谢谢 @pandolia 对项目的维护，太可惜了

**Comment by yuxiangyunei** [comment]
真是太可惜了，不知道除了hook手机端qq，还有没有其他办法做qqbot

**Comment by pandolia** [comment]
感谢各位的支持！

**Comment by heye0507** [comment]
非常感谢 @pandolia 
很遗憾腾讯关闭smartqq, 今天刚把相关代码平移到微信.

还是很感谢一直以来对qqbot的维护！

**Comment by Shroudfzj** [comment]
感谢 @pandolia 对项目的维护。可惜没有用到这么好的东西

**Comment by takumashin** [comment]
居然还能用，接口没有关。。。

**Comment by liang55** [comment]
今天关闭了吧 我的已经登录不上去了

**Comment by YuanYunGuoYan** [comment]
这就尴尬了，我刚刚接到公司需求要做相应发送QQ消息，就看到这消息(¬_¬)

**Comment by Keyto1995** [comment]
有没有什么替代的解决方案？

**Comment by lovesnow** [comment]
@pandolia 已经停了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by aRe00t** [comment]
感谢作者的付出

**Comment by AsukaSong** [comment]
感谢 @pandolia

**Comment by xiaobear250** [comment]
@pandolia 多谢您多年对这个项目的付出！！

**Comment by pzli** [comment]
今天登陆会显示
第5次请求“https://s.web2.qq.com/api/getvfwebqq”时出现 网络错误 HTTPSConnectionPool(host='s.web2.qq.com', port=443): Max retries exceeded with url: /api/getvfwebqq?ptwebqq=0c74b7290340ccdb52025438251971faba621694d1ca478dcefe2ef1463b82c9&clientid=53999199&psessionid=&t=0.07650326141321218 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))), html=''

**Comment by Joxon** [comment]
腾讯已经关闭了webqq接口。

[DEBUG] 第1次请求“https://s.web2.qq.com/api/getvfwebqq”时出现 网络错误 HTTPSConnectionPool(host='s.web2.qq.com', port=443): Max retries exceeded with url: /api/getvfwebqq?ptwebqq=a3d1f096f2374156eb7d66152f973461aff7f3a2be8916e6bdac1b0b15f780fc&clientid=53999199&psessionid=&t=0.8200593555595795 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faf6c3ae6a0>: Failed to establish a new connection: [Errno 22] Invalid argument',))，html=''

感谢 @pandolia 。

**Comment by matrixxxxxx** [comment]
代替的方案可以选择酷Q，自己写插件。

**Comment by chengyinjie** [comment]
谢谢作者，帮助了很多人

**Comment by ipydeal** [comment]
还没用就结束了，心态崩了

**Comment by ZhelinCheng** [comment]
> 代替的方案可以选择酷Q，自己写插件。

酷Q好像不能跨平台

**Comment by 849430904** [comment]
好可惜

**Comment by gongel** [comment]
泪目

**Comment by gylidian** [comment]
> > 代替的方案可以选择酷Q，自己写插件。
> 
> 酷Q好像不能跨平台

有Docker

**Comment by weathon** [comment]
https://github.com/richardchien/nonebot
这个似乎是唯一幸存的了
